config/routes.rb
Rails.application.routes.draw do
  # Routes for main resources
  resources :project_roles do
    collection do
      get 'user_names'
    end
  end
  resources :projects do
    collection do
      get 'categories'
      get 'genre'
      get 'set_last_proj'
    end
  end
  resources :users
  resources :sessions

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  
  # Authentication routes
  get 'user/edit' => 'users#edit', as: :edit_current_user
  get 'signup' => 'users#new', as: :signup
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy

  # Set the root url
  root :to => 'home#home'  
end

app/views/partials/login/_login_form.html.erb
<h3>Log In</h3>

<li><%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %></li>
<li><%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %></li>
<li><%= link_to "Sign in with Medium", "/auth/medium", id: "sign_in" %></li>

    <%= form_tag sessions_path do %>
      <div class="control-group">
        <div class="controls">
          <%= text_field_tag :username, params[:username], input_html: { placeholder:"Username" } %>
        </div>
      </div>

      <div class="control-group">
        <%= label_tag :password %>
        <div class="controls">
          <%= password_field_tag :password %>
        </div>
      </div>
      
      <div class="actions"><%= submit_tag "Log In", class: 'button secondary' %></div>
    <% end %>

<button class="close-button" data-close aria-label="Close modal" type="button">
  <span aria-hidden="true">&times;</span>
</button>

app/views/partials/login/_login_nav_link.html.erb
<!-- link to login -->
<% if !logged_in? %>
    <%= link_to(login_path, class: 'login', remote: true) do %> 
        <a href="#modal1" class="waves-effect waves-light modal-trigger"><h5>LOGIN</h5></a>
    <% end %>
    <div id="modal1" class="modal">            
        <%= render :partial => "partials/login/login_signup" %>
        <
<% end %>

<!-- options for logged in user -->
<% if logged_in? %>
    <%= link_to current_user.first_name, user_path(current_user), class: 'login' %> :: <%= link_to "Logout", logout_path, class: 'login' %>
<% end %>

app/views/partials/login/_login_signup.html.erb
<div class="modal-content">

    <div class="row">
        <div class="col s12">
          <ul class="tabs">
            <li class="tab col s3"><a href="#tab1">Log In</a></li>
            <li class="tab col s3"><a class="active" href="#tab2">Sign Up</a></li>
          </ul>
        </div>
        <div id="tab1" class="col s12">
            <%= render :partial => "partials/login/login_form" %>
        </div>
        <div id="tab2" class="col s12">
            <%= render :partial => "partials/login/signup_form" %>
        </div>
      </div>

</div>

app/views/partials/login/_signup_form.html.erb
<a href="#" class="accordion-title">1. Project <span>Step 1 of 2</span></a>
<div id="school-form">
  <div class="row">
    <div class="small-12 columns">

      <%= simple_form_for Project.new, remote: true  do |f| %>
        <%= f.input :title, input_html: { placeholder:"Name" }, label: false %>
        <%= f.input :category, input_html: { placeholder:"Street 1" }, label: false %>
        <%= f.input :genre, input_html: { placeholder:"Street 2" }, label: false %>
        <%= f.input :proj_description, input_html: { placeholder:"City" }, label: false %>
        <%= submit_tag "Submit and Continue", class: 'secondary button expanded' %>
      <% end %>

    </div>
  </div>
</div>

<a href="#" class="accordion-title">2. Account <span>Step 2 of 2</span></a>
<div id="user-form">
  <div class="row">
    <div class="small-12 column">

      

    </div>
  </div>
</div>