config/routes.rb
Rails.application.routes.draw do
  # Routes for main resources
  resources :project_roles do
    collection do
      get 'user_names'
    end
  end
  resources :projects do
    collection do
      get 'categories'
      get 'genre'
      get 'set_last_proj'
    end
  end
  resources :users
  resources :sessions

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  
  # Authentication routes
  get 'user/edit' => 'users#edit', as: :edit_current_user
  get 'signup' => 'users#new', as: :signup
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy

  # Set the root url
  root :to => 'home#home'  
end

app/views/partials/_flash.html.erb
<% flash.each do |name, msg| %>
<!-- <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box <%= flash[:notice] ? "success" : "warning" %> radius">
  <a href="#" class="close">&times;</a>
  <%#= msg %>
</div> -->
<script>Materialize.toast('<%= msg %>', 4000)</script>
<% end %>

app/views/partials/_footer.html.erb
<div class="row">
	<div class="col l6 s12">
		<h5>Writer.pub</h5>
		<p>insert footer content here.</p>
	</div>
	<div class="col l4 offset-l2 s12">
		<ul>
		<li><%= link_to 'Home', home_path %></li>
		<li><%= link_to 'About Writer.pub', about_path %></li>
		<li><%= link_to 'Contact Us', contact_path %></li>
		<li><%= link_to 'Privacy Policy', privacy_path %></li>
		</ul>
	</div>
</div>
</div>
<div class="footer-copyright">
	<div class="container">
		Webmaster: <%= mail_to("jbfields@andrew.cmu.edu", "Juliann Fields", encode: "javascript") %>&nbsp;&copy 2017
	</div>
</div>	

app/views/partials/_home_slider.html.erb
    <div class="carousel carousel-slider" data-indicators="true">
        
        <div class="carousel-item white black-text center" href="#one!">
            <%= image_tag  "typewriter.jpg" %>
        </div>
        
        <div class="carousel-item white black-text center" href="#two!">
            <h2>Second Panel</h2>
            <p class="black-text">This is your second panel</p>
        </div>
    </div>

app/views/partials/_nav.html.erb
<nav class="nav-extended">
  <div class="nav-wrapper"> 
    <%= link_to image_tag('logo.png'), home_path, class: 'brand-logo center' %>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    
    <ul id="nav-mobile" class="hide-on-med-and-down">
      <div class="left">
        <%= render :partial => 'partials/nav/base_nav_left' %>
      </div>
      <div class="right">
        <%= render :partial => 'partials/nav/base_nav_right' %>
      </div>
    </ul>
    
    <ul class="side-nav" id="mobile-demo">
      <!-- options for items -->
      <li>
        <%= link_to(about_path) do %>
          <h5>CATEGORIES</h5>
        <% end %>
      </li>
      
      <!-- options for Contact -->
      <li>
        <%= link_to(about_path) do %>
          <h5>READ</h5>
        <% end %>
      </li>
      
      <li>
        <%= link_to(new_project_path) do %>
          <h5>WRITE</h5>
        <% end %>
      </li>
      
      <!-- library -->
      <li>
        <% if logged_in? %>
          <%= link_to(about_path) do %>
            <h5>BOOKSHELF</h5>
          <% end %>
        <% end %>
      </li>
      
      <!-- login/accont options -->
      <li>
        <% if logged_in? %>
          <%= link_to(logout_path) do %>
            <h5>LOGOUT</h5>
          <% end %>
        <% else %>
          <%= link_to(login_path) do %>
            <h5>LOGIN</h5>
          <% end %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>
<br>
<div class="divider"></div>