config/routes.rb
Rails.application.routes.draw do
  # Routes for main resources
  resources :project_roles do
    collection do
      get 'user_names'
    end
  end
  resources :projects do
    collection do
      get 'categories'
      get 'genre'
      get 'set_last_proj'
    end
  end
  resources :users
  resources :sessions

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  
  # Authentication routes
  get 'user/edit' => 'users#edit', as: :edit_current_user
  get 'signup' => 'users#new', as: :signup
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy

  # Set the root url
  root :to => 'home#home'  
end

app/models/project.rb
class Project < ActiveRecord::Base
    # Relationships
    # -----------------------------
    belongs_to :owner, class_name: "User", foreign_key: "user_id"
    has_many :project_roles
    has_many :roles, through: :project_roles
    has_many :users, through: :project_roles

    STATUS = %w[active hiatus finished cancelled]
    PREVIEW_LEVEL = %w[hidden by_invitation preview published]

    accepts_nested_attributes_for :project_roles, reject_if: lambda { |project_role| project_role[:user_id].blank? }, allow_destroy: true        

    # scopes
    # -----------------------------
    scope :alphabetical,  -> { order("title") }
    scope :chronological, -> { order("start_date") }
    scope :by_owner,      -> { joins(:owner).order('users.last_name').order('users.first_name')}
    scope :active,        -> { where("start_date <= ? and (end_date > ? or end_date is null)", Date.today, Date.today) }
    scope :completed,     -> { where("end_date <= ?", Date.today) }
    scope :for_title,     -> (title) { where("title LIKE ?", "#{title}%") }
    scope :for_owner,     -> (owner_id) { joins(:owner).where("users.id = ?", owner_id)}
	scope :for_category,  -> (category) { where('category = ?', category) }
    scope :for_genre,     -> (genre) { where('genre = ?', genre) }

    # Validations
    # -----------------------------
    validates_presence_of :title
    validates_presence_of :status
    validates_presence_of :genre
    validates_presence_of :category
    validates_uniqueness_of :title
    validates_inclusion_of :status, in: %w[active hiatus finished cancelled], message: "is not included in list of accepted status"
    validates_inclusion_of :preview_level, in: %w[hidden by_invitation preview published], message: "is not included in list of accepted preview levels"
    validates_date :start_date, on_or_before:  lambda { Date.current }
    validates_date :end_date, after: :start_date, allow_blank: true
    validate :is_unique_project?

    # Callbacks
    # -----------------------------
    before_save :is_ended?
    # before_save :owner_is_active

    # Additional Methods
    # -----------------------------
    def time_length
        unless self.end_date.nil?
            return (self.end_date - self.start_date).to_i
        end
        return (Date.today - self.start_date).to_i
    end

    def cancel
        self.end_date = Date.today
        self.status = "cancelled"
        self.save!
    end

    def owner_is_active
        return owner.active
    end

    def is_unique_project?
        return Project.for_title(self.title).for_owner(self.owner)
    end 

    def is_ended?
        if self.status == "finished" && self.end_date.nil?
            self.end_date = Date.today
        end
    end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    # before_action :check_login, except [:index, :show]   
    before_action :set_project, only: [:show, :edit, :update, :destroy]
    # respond_to :js, :html, :json

    def index
        @active_projects = Project.active.chronological.alphabetical.paginate(page: params[:page]).per_page(10)
        @completed_projects = Project.completed.chronological.alphabetical.paginate(page: params[:page]).per_page(10)
        @all_projects = Project.chronological.alphabetical#.paginate(page: params[:page]).per_page(10)
    end

    def show
        @project_team = @project.project_roles.filled
    end

    def new
        @project = Project.new
        @project.project_roles.build
        @last_project = Project.last
    end

    def edit
    end

    def categories
        @categories = Project.all.map{|p|p.category}.sort
        respond_to do |format|
            format.json {render json: @categories}
        end
    end

    def genre
        @categories = Project.all.map{|p|p.genre}.sort
        respond_to do |format|
            format.json {render json: @categories}
        end
    end

    def set_last_proj
        @last_project = Project.find(params[:project_id])
    end

    def create
        @project = Project.new(project_params)
        @project.start_date = Date.today
        @project.owner = @current_user  # set the owner to the user who created the project
    
        if @project.save
            # if saved to database
            @last_project = @project
            logger.info(@last_project.id)
            respond_to do |format|
                format.html { redirect_to @project, notice: "#{@project.title} has been created." }
                format.js {}
            end
        else
            # return to the 'new' form
			flash[:error] = "This project could not be created."
            render :action => 'new'
        end
    end

    def update
        if @project.update(project_params)
            flash[:notice] = "#{@project.title} has been updated."
            redirect_to @project
        elsif
            logger.info("last project ID is: ")
            logger.info(@last_project.id)
            @last_project.update(project_params)
            flash[:notice] = "#{@last_project.title} has been updated."
            redirect_to @last_project
        else
            render :action => 'edit'
        end
    end

    def destroy
        @project.destroy
        flash[:notice] = "Successfully removed #{@project.title}."
        redirect_to projects_url        
    end

    private

    def set_project
        @project = Project.find(params[:id])
    end

    def project_params
        params.fetch(:project, {}).permit(:proj_description, :genre, :title, :category, :preview_level, :status, :start_date, :owner)
        # params.fetch[:start_date] = Date.today
        # params.fetch[:owner] = @current_user
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for @project, :html => { :class => 'form-horizontal' } do |f| %>
  <!-- error handling -->
  <% if @project.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
    
    <ul>
      <% @project.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <form class="col s12">
    <legend><%= controller.action_name.capitalize %> Project</legend>

    <div class="row">
        <div class="input-field col s12">
          <%= f.input :title, :params => :title %>
        </div>
    </div>

    <div class="row">
        <div class="input-field col s12">
          <%= f.input :category, :params => :category %>
        </div>
    </div>

    <div class="row">
        <div class="input-field col s12">
          <%= f.input :genre, :params => :genre %>
        </div>
    </div>

    <div class="row">
        <div class="input-field col s12">
          <%= f.input :proj_description, class:"materialize-textarea", :'data-length' => 200 %>
        </div>
    </div>

    <div class="row">
        <div class="input-field col s12">
          <%= f.input :preview_level %>
        </div>
    </div>

    <div class="row">
        <div class="input-field col s12">
          <%= f.input :status %>
        </div>
    </div>

    <div class="form-actions row">
      <div class="waves-effect waves-light btn right">  
        <%= f.submit nil %>
      </div>
      <div class="waves-effect waves-light btn left">
          <%= link_to 'Back', projects_path %>
      </div>
    </div>
  </form>

  <br><br>
  
<% end %>

app/views/projects/_project_basics_form.html.erb
<%= simple_form_for @project, remote: true, :html => { :class => 'form-horizontal', :id => 'projectSubmit' } do |f| %>
    <!-- error handling -->
    <% if @project.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
            
            <ul>
                <% @project.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="row">
        <div class="input-field col s12">
            <%= f.input :title, :params => :title %>
        </div>
    </div>

    <div class="row">
        <div class="input-field col s12">
            <%= f.input :category, :params => :category %>
        </div>
    </div>

    <div class="row">
        <div class="input-field col s12">
            <%= f.input :genre, :params => :genre %>
        </div>
    </div>

    <div class="row">
        <div class="input-field col s12">
            <%= f.input :proj_description, class:"materialize-textarea", :'data-length' => 150 %>
        </div>
    </div>

    <div class="form-actions row">
        <div class="waves-effect waves-light btn right">  
            <%= f.submit "Next" %>
        </div>
        <div class="waves-effect waves-light btn left">
            <%= link_to 'Back', home_path, :class => "white-text" %>
        </div>
    </div>
<% end %>

app/views/projects/_project_settings_form.html.erb
<%# @last_project = Project.find(Project.last.id+1) %>
<%= simple_form_for @last_project, :html => {:class => 'form-horizontal', :id => "project_settings_form", } do |f| %>
    <div class="row">
        <div class="input-field col s12">
            <%= f.select :preview_level, collection: Project::PREVIEW_LEVEL %>
        </div>
    </div>

    <div class="row">
        <div class="input-field col s12">
            <%= f.select :status, collection: Project::STATUS %>
        </div>
    </div>

    <div class="form-actions row">
        <div class="waves-effect waves-light btn right">  
            <%= f.submit %>
        </div>

        <div class="waves-effect waves-light btn left">
            <a onclick="$(document).ready(function(){$('ul.tabs').tabs('select_tab', 'Members');});">
                BACK
            </a>
        </div>
    </div>
<% end %>

app/views/projects/_project_tabbed_form.html.erb
<div class="row">
  <div class="tabs-vertical">
    <div class="col s5 m4 l2">
      <ul class="tabs">
        <li class="tab">
          <a href="#Basics" class="active">BASICS</a>
        </li>
        <li class="tab">
          <a href="#Members">MEMBERS</a>
        </li>
        <li class="tab">
          <a href="#Settings">SETTINGS</a>
        </li>
      </ul>
    </div>
    
    <div class="col s8 m9 l8">
      <!-- BASICS TAB -->
      <div id="Basics" class="tab-content">
        <%= render  "project_basics_form" %>
      </div>
      
      
      <!-- MEMBERS TAB -->
      <div id="Members" class="tab-content">
        <div>
            <%= render :partial => "project_roles/list_of_members" %>            
        </div>
        <div>
            <%= render :partial => "project_roles/project_roles_fields" %>
        </div>
      </div>
      
      <!-- SETTINGS TAB -->
      <div id="Settings" class="tab-content">
        <%= render :partial => "project_settings_form" %>
      </div>  
    </div>
  </div>
</div>

app/views/projects/create.js.erb
$('form#projectSubmit').on('ajax:complete', function(result) {
    // $('form#project_settings_form').reload()
    updateProject('<%= @project.id %>');
    $('ul.tabs').tabs('select_tab', 'Members');
});


function updateProject (id) {
    $.ajax({
        type: "GET",
        url: "set_last_proj",
        data: {project_id: id}
    });
}

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col m4 s5">
    <h4>Public Projects</h4>
  </div>
  <div class="search col m8 s7">
    <input type="text" class="queue-search input-field" placeholder="Search" width="300px"/>
  </div>  
</div>

<div class="section">
  <div class="divider"></div>
  
  <div class="section row center-align">
    <div class="row queue-search">
      <% @all_projects.each do |project| %>    
        <div class="col s4">
          <div class="card horizontal search-card" style="height:240px;">
            <div class="card-image">
              <%= image_tag  "bookcover.jpg" %>
              <span class="card-title"><%= link_to project.title, project, class: "white-text" %></span>
            </div>
            <div class="card-stacked">
              <div class="card-content">
                <span class="card-title grey-text text-darken-4"><%= link_to project.category, project %><p class="grey-text"> - <%= project.genre %> - </p></span>
                <p class="left-align"><%= project.proj_description %></p>
              </div>
              <div class="card-action">
                <a class="btn-floating waves-effect waves-light red right" ><i class="tiny material-icons">bookmark_border</i></a>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="section">
  <%= link_to 'Create Something New!', new_project_path, class: "center green accent-1 btn" %>
</div>
<br>
<br>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render  "project_tabbed_form" %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<div class="section">
    <div class="row">
        <div class="card  col s4">
            <div class="card-image">
                <%= image_tag  "bookcover.jpg" %>
                <span class="card-title">
                    <%= @project.title %>
                    <p class="grey-text"> - <%= @project.genre %> - </p>
                </span>
            </div>
            <div class="card-content">
                <p><%= @project.proj_description %></p>
            </div>
            <div class="card-action">
                <a href="#">This is a link</a>
            </div>
        </div>
        <div class="col s1"></div>
        <div class="card small col s7">
            <div class="card-content">
                <span class="card-title"><h5>Additional Info</h5></span>
                <div class="container">
                    <table>
                        <thead>
                            <th colspan="2"></th>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <p><b>Dates: </b></p>
                                </td>
                                <td>
                                    <p><%= @project.start_date %> - <% if @project.end_date.nil? %> continuing <% else %> <%= @project.end_date %> <% end %></p>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <p><b>Category: </b></p>
                                </td>
                                <td>
                                    <p><%= @project.category %></p>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <p><b>Work Status: </b></p>
                                </td>
                                <td>
                                    <p><%= @project.status %></p>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <p><b>Publicity Status: </b></p>
                                </td>
                                <td>
                                    <p><%= @project.preview_level %></p>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col s1"></div>
        <div class="card small col s7">
            <div class="card-content">
                <span class="card-title"><h5>Participants</h5></span>
                <div class="container">
                    <table>
                        <thead>
                            <th>Name</th>
                            <th>Role</th>
                        </thead>
                        <tbody>
                            <% unless @project.owner.nil? %>
                                <tr>
                                    <td>
                                        <%= @project.owner.name %>
                                    </td>
                                    <td>
                                        Owner
                                    </td>
                                </tr>
                            <% end %>
                            <% @project_team.each do |member| %>
                                <tr>
                                    <td>
                                        <%= member.user.name %>
                                    </td>
                                    <td>
                                        <%= member.role.name %>
                                    </td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    
    <%= link_to 'Edit', edit_project_path(@project) %> |
    <%= link_to 'Back', projects_path %>
</div>
</div>