config/routes.rb
Rails.application.routes.draw do
  # Routes for main resources
  resources :project_roles do
    collection do
      get 'user_names'
    end
  end
  resources :projects do
    collection do
      get 'categories'
      get 'genre'
      get 'set_last_proj'
    end
  end
  resources :users
  resources :sessions

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  
  # Authentication routes
  get 'user/edit' => 'users#edit', as: :edit_current_user
  get 'signup' => 'users#new', as: :signup
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy

  # Set the root url
  root :to => 'home#home'  
end

app/views/partials/nav/_base_nav.html.erb
<!-- link to home -->
<li>
  <%= link_to(home_path) do %>
    <h5>HOME</h5>
  <% end %>
</li>

<!-- options for items -->
<li>
  <%= link_to(about_path) do %>
    <h5>CATEGORIES</h5>
  <% end %>
</li>

<!-- options for Contact -->
<li>
  <%= link_to(about_path) do %>
    <h5>READ</h5>
  <% end %>
</li>

<li>
  <%= link_to(new_project_path) do %>
    <h5>WRITE</h5>
  <% end %>
</li>

<!-- library -->
<li>
    <% if logged_in? %>
      <%= link_to(about_path) do %>
        <h5>BOOKSHELF</h5>
      <% end %>
    <% end %>
  </li>

<!-- login/accont options -->
<li>
  <% if logged_in? %>
    <%= link_to(logout_path) do %>
      <h5>LOGOUT</h5>
    <% end %>
  <% else %>
    <%= link_to(login_path) do %>
      <h5>LOGIN</h5>
    <% end %>
  <% end %>
</li>

app/views/partials/nav/_base_nav_left.html.erb
<!-- options for items -->
<!-- <li>
    <%#= link_to(projects_path) do %>
    <h5>CATEGORIES</h5>
    <%# end %>
</li> -->

<!-- options for Contact -->
<li>
    <%= link_to(projects_path) do %>
    <h5>READ</h5>
    <% end %>
</li>

app/views/partials/nav/_base_nav_right.html.erb
<li>
  <%= link_to(new_project_path) do %>
  <h5>WRITE</h5>
  <% end %>
</li>

<!-- library -->
<li>
  <% if logged_in? %>
  <%= link_to(about_path) do %>
  <h5>BOOKSHELF</h5>
  <% end %>
  <% end %>
</li>

<!-- login/accont options -->
<li>
  <div class="fixed-action-btn">
    <%= image_tag  "account_icon.png", class:"btn-floating btn-large" %>
    <ul>
      <li>
        <% if logged_in? %>
          <%= link_to user_path(current_user), class:"btn-floating black" do %>
          <i class="material-icons">person_pin</i>
          <% end %>
        <% end %>
      </li>
      <li>
          <% if logged_in? %>
            <%= link_to logout_path, class:"btn-floating black" do %>
              <i class="material-icons">lock</i>
            <% end %>
          <% else %>
            <%= link_to login_path, class:"btn-floating black" do %>
              <i class="material-icons">person_pin</i>
            <% end %>
          <% end %>
      </li>
      <% if logged_in? %>
        <li><a class="btn-floating black"><i class="material-icons">collections_bookmark</i></a></li>
        <li><a class="btn-floating black"><i class="material-icons">mail</i></a></li>
        <% end %>
    </ul>
  </div>
</li>